# INSERT INTO main_models_nationality (id, nationality)
# VALUES
# (1, 'Argentina'),
# (2, 'Armenia'),
# (3, 'Aruba'),
# (4, 'Australia'),
# (5, 'Austria'),
# (6, 'Azerbaijan'),
# (7, 'Bahamas'),
# (8, 'Bahrain'),
# (9, 'Bangladesh'),
# (10, 'Barbados'),
# (11, 'Belarus'),
# (12, 'Belgium'),
# (13, 'Belize'),
# (14, 'Benin'),
# (15, 'Bermuda'),
# (16, 'Bhutan'),
# (17, 'Bulgaria'),
# (18, 'BurkinaFaso'),
# (19, 'Burundi'),
# (20, 'Cambodia'),
# (21, 'Cameroon'),
# (22, 'Canada'),
# (23, 'CapeVerde'),
# (24, 'CaymanIslands'),
# (25, 'Colombia'),
# (26, 'Comoros'),
# (27, 'Congo'),
# (28, 'CookIslands'),
# (29, 'CostaRica'),
# (30, 'Côted'),
# (31, 'Ivoire'),
# (32, 'Croatia'),
# (33, 'Cuba'),
# (34, 'Curaçao'),
# (35, 'Cyprus'),
# (36, 'CzechRepublic'),
# (37, 'Denmark'),
# (38, 'Djibouti'),
# (39, 'Dominica'),
# (40, 'DominicanRepublic'),
# (41, 'Ecuador'),
# (42, 'Egypt'),
# (43, 'Guadeloupe'),
# (44, 'Guam'),
# (45, 'Guatemala'),
# (46, 'Guernsey'),
# (47, 'Guinea'),
# (48, 'Guinea - Bissau'),
# (49, 'Guyana'),
# (50, 'Haiti'),
# (51, 'Honduras'),
# (52, 'HongKong'),
# (53, 'Hungary'),
# (54, 'Iceland'),
# (55, 'India'),
# (56, 'Indonesia'),
# (57, 'Norway'),
# (58, 'Oman'),
# (59, 'Pakistan'),
# (60, 'Palau'),
# (61, 'Panama'),
# (62, 'PapuaNewGuinea'),
# (63, 'Paraguay'),
# (64, 'Peru'),
# (65, 'Philippines'),
# (66, 'Pitcairn'),
# (67, 'Poland'),
# (68, 'Portugal'),
# (69, 'PuertoRico'),
# (70, 'Qatar'),
# (71, 'Réunion'),
# (72, 'Romania'),
# (73, 'RussianFederation'),
# (74, 'Rwanda'),
# (75, 'Swaziland'),
# (76, 'Sweden'),
# (77, 'Switzerland'),
# (78, 'Turkey'),
# (79, 'Turkmenistan'),
# (80, 'Tuvalu'),
# (81, 'Uganda'),
# (82, 'Ukraine'),
# (83, 'UnitedKingdom'),
# (84, 'UnitedStates'),
# (85, 'Uruguay'),
# (86, 'Uzbekistan'),
# (87, 'Yemen'),
# (88, 'Zambia'),
# (89, 'Zimbabwe');


# INSERT INTO main_Models_company_category (id, company_category)
# VALUES
# (1, 'Transportation'),
# (2, 'Hospital'),
# (3, 'Banking Company'),
# (4, 'Grocery Shop'),
# (5, 'Software Company'),
# (6, 'Customer Care Center'),
# (7, 'Ecommerce Platform'),
# (8, 'Food Manufacturer'),
# (9, 'Food Quality Assurance Company'),
# (10, 'PC Repair Shop'),
# (11, 'Mechanic Shop'),
# (12, 'Telephone Company'),
# (13, 'Cloud Engineering'),
# (14, 'Hotel Business'),
# (15, 'Pharmaceutical Company'),
# (16, 'Accounting Firm'),
# (17, 'IoT Company'),
# (18, 'Security Services'),
# (19, 'Roads & Highways'),
# (20, 'Library'),
# (21, 'Digital Marketing Services'),
# (22, 'R & D Company'),
# (23, 'Edtech Company'),
# (24, 'Newspaper'),
# (25, 'Book Publishers');


# INSERT INTO main_Models_job_category (id, job_category)
# VALUES
# (1, 'Heavy and Tractor-Trailer Truck Drivers'),
# (2, 'Registered Nurses'),
# (3, 'First-Line Supervisors of Retail Sales Workers'),
# (4, 'Retail Salespersons'),
# (5, 'Software Developers, Applications'),
# (6, 'Customer Service Representatives'),
# (7, 'Marketing Managers'),
# (8, 'First-Line Supervisors of Food Preparation and Serving Workers'),
# (9, 'First-Line Supervisors of Office and Administrative Support Workers'),
# (10, 'Computer User Support Specialists'),
# (11, 'Computer Systems Analysts'),
# (12, 'Network and Computer Systems Administrators'),
# (13, 'Web Developers'),
# (14, 'Management Analysts'),
# (15, 'Medical and Health Services Managers'),
# (16, 'Accountants'),
# (17, 'Information Technology Project Managers'),
# (18, 'Sales Managers'),
# (19, 'Industrial Engineers'),
# (20, 'Executive Secretaries and Executive Administrative Assistants'),
# (21, 'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products'),
# (22, 'Maintenance and Repair Workers, General'),
# (23, 'Social and Human Service Assistants'),
# (24, 'Entrepreneurs Wanted – Business Opportunities'),
# (25, 'First-Line Supervisors of Production and Operating Workers'),
# (26, 'Nursing Assistants'),
# (27, 'Combined Food Preparation and Serving Workers, Including Fast Food'),
# (28, 'Licensed Practical and Licensed Vocational Nurses'),
# (29, 'General and Operations Managers'),
# (30, 'Bookkeeping, Accounting, and Auditing Clerks'),
# (31, 'Managers, All Other'),
# (32, 'Financial Managers, Branch or Department'),
# (33, 'Insurance Sales Agents'),
# (34, 'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products'),
# (35, 'Sales Representatives, Services, All Other'),
# (36, 'Sales Agents, Financial Services'),
# (37, 'Critical Care Nurses'),
# (38, 'Cashiers'),
# (39, 'Computer Systems Engineers/Architects'),
# (40, 'Market Research Analysts and Marketing Specialists'),
# (41, 'Physical Therapists'),
# (42, 'Medical Assistants'),
# (43, 'First-Line Supervisors of Non-Retail Sales Workers'),
# (44, 'Software Quality Assurance Engineers and Testers'),
# (45, 'First-Line Supervisors of Mechanics, Installers, and Repairers'),
# (46, 'Information Security Analysts'),
# (47, 'Medical Secretaries'),
# (48, 'Laborers and Freight, Stock, and Material Movers, Hand'),
# (49, 'Security Guards'),
# (50, 'Family and General Practitioners');


# 404
# index

# freelancers-search-companies, 'Search Companies', 'Employee', 'Search Companies'
# freelancers-browse-jobs, 'Browse Jobs', 'Employee', 'Browse Jobs'
# freelancers-job-proposals, 'Job Proposals', 'Employee', 'Job Proposals'

# employers-search-freelancers, 'Search Employee', 'Employers', 'Search Employee'
# employers-post-a-company, 'Post a Company', 'Employers', 'Post a Company'
# employers-post-a-job, 'Post a Job', 'Employers', 'Post a Job'
# employers-manage-jobs, 'Manage Jobs', 'Employers', 'Manage Jobs'
# employers-manage-candidates, 'Manage Candidates', 'Employers', 'Manage Candidates'

# account-settings, 'Settings', 'Account', 'Settings'

# about-us#contact, 'Contact', 'About Us', 'Contact'
# about-us#privacy_policies, Privacy Policies: About Us, Privacy Policies
# about-us#terms_of_use, Terms of Use: About Us, Terms of Use