# Generated by Django 3.2.6 on 2021-12-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models_freelancer',
            name='freelancer_name',
        ),
        migrations.AddField(
            model_name='models_freelancer',
            name='freelancer_name_first',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='models_freelancer',
            name='freelancer_name_last',
            field=models.TextField(default='-'),
        ),
    ]
