# Generated by Django 3.2.6 on 2021-12-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211225_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_freelancer',
            name='freelancer_name_first',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='models_freelancer',
            name='freelancer_name_last',
            field=models.TextField(),
        ),
    ]
