# Generated by Django 3.2.6 on 2021-12-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211225_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='models_freelancer',
            name='emailaddress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='models_freelancer',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
